##
# Build Stage - This image won't be included in the release image. Only compiles.
##
FROM maven:3.6.1-jdk-8 AS build
COPY app /usr/src/app
RUN mvn -f /usr/src/app/pom.xml clean package

##
# Package stage
## 
FROM openjdk:8u212-slim
COPY --from=build /usr/src/app/target/my-java-app-0.0.1-SNAPSHOT.jar /usr/src/myapp/my-java-app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/usr/src/myapp/my-java-app.jar"]
