# Use Java11 as parent image
FROM openjdk:11.0.3

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into container's /app
ADD . /app

# Make port 80 available to the world outside this container
EXPOSE 80
